name: Pug Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - name: Install dependencies
        run: |
          npm install pug -g
          npm install pug-cli -g 

      - name: Check contents of directory
        run: |
          ls -al
          ls -al ./web
        
      - name: Build Pug files
        run: |
          pug web/index.pug
          ls -al ./web
          cp web/index.html ./ 